import {
  spfOne,
  productOneImg1,
  productOneImg2,
  productOneImg3,
  productOneImg4,
  productTwoImg1,
  productTwoImg2,
  productTwoImg3,
  productTwoImg4,
  productThreeImg1,
  productThreeImg2,
  productThreeImg3,
  productThreeImg4,
  productThreeImg5,
  productFourImg1,
  productFourImg2,
  productFourImg3,
  productFourImg4,
  productFourImg5,
  productFiveImg6,
  productFiveImg5,
  productFiveImg4,
  productFiveImg3,
  productFiveImg2,
  productFiveImg1,
  productSixImg7,
  productSixImg8,
  productSixImg6,
  productSixImg5,
  productSixImg4,
  productSixImg3,
  productSixImg2,
  productSixImg1,
  productSevenImg1,
  productSevenImg2,
  productSevenImg3,
  productSevenImg4,
  productSevenImg5,
  productSevenImg6,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Cart",
    link: "/cart",
  },

  {
    _id: 1003,
    title: "Contact",
    link: "contact",
  },
];
// =================== NavBarList End here ======================

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 100,
    img: [productOneImg1, productOneImg2, productOneImg3, productOneImg4],
    productName: "Nike AF1 full black",
    price: "199.00",
    size: 41,
    condition: 7.5,
    badge: true,
    des: "",
  },
  {
    _id: 101,
    img: [productTwoImg1, productTwoImg2, productTwoImg3, productTwoImg4],
    productName: "Nike AF1 React DMSX",
    price: "199.00",
    size: 41,
    badge: true,
    condition: 7,
    des: "",
  },
  {
    _id: 102,
    img: [
      productThreeImg1,
      productThreeImg2,
      productThreeImg3,
      productThreeImg4,
      productThreeImg5,
    ],
    productName: "Nike Lunarglide 6",
    price: "300.00",
    badge: true,
    size: 41,
    condition: 7,
    des: "",
  },

  {
    _id: 103,
    img: [
      productFourImg1,
      productFourImg2,
      productFourImg3,
      productFourImg4,
      productFourImg5,
    ],
    productName: "Jack & Jones Bane Sneakers ",
    price: "300.00",
    badge: true,
    size: 40,
    condition: 5,
    des: "Slightly cushioned footbed for added comfort ",
  },
  {
    _id: 104,
    img: [
      productFiveImg1,
      productFiveImg2,
      productFiveImg3,
      productFiveImg4,
      productFiveImg5,
      productFiveImg6,
    ],
    productName: "Nike AF1 full white ",
    price: "300.00",
    badge: true,
    size: 40,
    condition: 8.5,
    des: "",
  },
  {
    _id: 105,
    img: [
      productSixImg1,
      productSixImg2,
      productSixImg3,
      productSixImg4,
      productSixImg5,
      productSixImg6,
      productSixImg7,
      productSixImg8,
    ],
    productName: "Nike Levron James 16 WTL limted edtion ",
    price: "900.00",
    badge: true,
    size: 40,
    condition: 10,
    des: "",
  },
  {
    _id: 106,
    img: [
      productSevenImg1,
      productSevenImg2,
      productSevenImg3,
      productSevenImg4,
      productSevenImg5,
      productSevenImg6,
    ],
    productName: "Valentino Granvani",
    price: "1200.00",
    badge: true,
    size: 41,
    condition: 9.5,
    des: `Sneakers open skate Leather White Green 
     Closure: Lace Up Closure 
     Made in italy 
      Heel heigh `,
  },
];
// =================== PaginationItems End here =================
